# Generated by Django 3.2.3 on 2021-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osMansoura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(default='first name', max_length=50),
        ),
    ]
